version: '3.9'

services:
  payara:
    image: payara/server-full:latest
    container_name: payara
    ports:
      - "8080:8080"
    volumes:
      - ./target/rent-data-1.0-SNAPSHOT.war:/opt/payara/deployments/rent-data.war